name = "beagles-basket-realtime-workar"
main = "src/index.js"
compatibility_date = "2026-06-23"

[[durable_objects.bindings]]
name = "beagles-basket-realtime-workar"
class_name = "beagles-basket-realtime-workar"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BasketRoom"]
